/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: 7fca3b332514f4674195c4ba30b551a5)
interface __BaseEnv_CloudflareBindings {
  AVATARS: R2Bucket;
  DB: D1Database;
  IMAGES: ImagesBinding;
  WECHAT_MINI_APP_ID: "wx02ce91659b1acef4";
  WEB_ORIGIN: string;
  SERVER_URL: string;
  BETTER_AUTH_SECRET: string;
  EASY_AUTH_CLIENT_ID: string;
  EASY_AUTH_CLIENT_SECRET: string;
  BGM_API_URL: string;
  WECHAT_MINI_APP_SECRET: string;
  WECHAT_CALLBACK_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface ProductionEnv {
    AVATARS: R2Bucket;
    DB: D1Database;
    IMAGES: ImagesBinding;
    WECHAT_MINI_APP_ID: "wx02ce91659b1acef4";
    WEB_ORIGIN: string;
    SERVER_URL: string;
    BETTER_AUTH_SECRET: string;
    EASY_AUTH_CLIENT_ID: string;
    EASY_AUTH_CLIENT_SECRET: string;
    BGM_API_URL: string;
    WECHAT_MINI_APP_SECRET: string;
    WECHAT_CALLBACK_TOKEN: string;
  }
  interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "WECHAT_MINI_APP_ID"
      | "WEB_ORIGIN"
      | "SERVER_URL"
      | "BETTER_AUTH_SECRET"
      | "EASY_AUTH_CLIENT_ID"
      | "EASY_AUTH_CLIENT_SECRET"
      | "BGM_API_URL"
      | "WECHAT_MINI_APP_SECRET"
      | "WECHAT_CALLBACK_TOKEN"
    >
  > {}
}
declare module "*.wasm" {
  const value: WebAssembly.Module;
  export default value;
}
declare module "*.ttf" {
  const value: ArrayBuffer;
  export default value;
}
