import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const shareDist = resolve(root, "share/dist");

const appPackage = JSON.parse(await readFile(resolve(root, "package.json"), "utf8")) as {
  version: string;
};
await writeFile(
  resolve(root, "mini/miniprogram/lib/app-version.ts"),
  `// Generated by scripts/prepare-mini.ts. Do not edit.\nexport const APP_VERSION = ${JSON.stringify(appPackage.version)};\n`,
);

const miniPackage = JSON.parse(await readFile(resolve(root, "mini/package.json"), "utf8")) as {
  dependencies?: Record<string, string>;
};
const projectConfig = JSON.parse(
  await readFile(resolve(root, "mini/project.config.json"), "utf8"),
) as {
  setting?: { packNpmManually?: boolean; packNpmRelationList?: unknown[] };
};

if (miniPackage.dependencies?.share !== "workspace:*") {
  throw new Error('mini/package.json 必须声明 "share": "workspace:*"。');
}
if (
  projectConfig.setting?.packNpmManually !== true ||
  !projectConfig.setting.packNpmRelationList?.length
) {
  throw new Error("mini/project.config.json 尚未配置手动 npm 构建。");
}

await rm(shareDist, { force: true, recursive: true });
await mkdir(shareDist, { recursive: true });

const build = await Bun.build({
  entrypoints: [resolve(root, "share/src/index.ts")],
  format: "cjs",
  naming: "index.js",
  outdir: shareDist,
  target: "browser",
});
if (!build.success) {
  throw new AggregateError(build.logs, "构建 share 的 Mini CommonJS 产物失败。");
}

const declarations = Bun.spawnSync({
  cmd: ["bunx", "tsc", "-p", resolve(root, "share/tsconfig.mini.json")],
  cwd: root,
  stderr: "inherit",
  stdout: "inherit",
});
if (declarations.exitCode !== 0) {
  throw new Error("生成 share 的 Mini 类型声明失败。");
}

const declarationsSource = await readFile(resolve(shareDist, "index.d.ts"), "utf8");
await writeFile(resolve(shareDist, "index.d.cts"), declarationsSource);
await writeFile(resolve(shareDist, "package.json"), '{"type":"commonjs"}\n');
console.log("Mini 准备完成：已生成 share/dist。请在微信开发者工具中执行「构建 npm」。");
