/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as TrustRouteImport } from './routes/_trust'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppScheduleRouteImport } from './routes/_app/_schedule'
import { Route as AppCollectionsRouteImport } from './routes/_app/collections'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as TrustAboutRouteImport } from './routes/_trust/about'
import { Route as TrustPrivacyRouteImport } from './routes/_trust/privacy'
import { Route as TrustTermsRouteImport } from './routes/_trust/terms'
import { Route as SitemapChaptersDotxmlRouteImport } from './routes/sitemap/chapters[.]xml'
import { Route as SitemapCharactersDotxmlRouteImport } from './routes/sitemap/characters[.]xml'
import { Route as SitemapCollectionsDotxmlRouteImport } from './routes/sitemap/collections[.]xml'
import { Route as SitemapPersonsDotxmlRouteImport } from './routes/sitemap/persons[.]xml'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap/static[.]xml'
import { Route as SitemapSubjectsDotxmlRouteImport } from './routes/sitemap/subjects[.]xml'
import { Route as AppScheduleIndexRouteImport } from './routes/_app/_schedule/index'
import { Route as AppChaptersChapterIdRouteImport } from './routes/_app/chapters/$chapterId'
import { Route as AppCharactersCharacterIdRouteImport } from './routes/_app/characters/$characterId'
import { Route as AppDiscoverIndexRouteImport } from './routes/_app/discover/index'
import { Route as AppDiscoverTypeRouteImport } from './routes/_app/discover/$type'
import { Route as AppPersonsPersonIdRouteImport } from './routes/_app/persons/$personId'
import { Route as AppRankingsIndexRouteImport } from './routes/_app/rankings/index'
import { Route as AppSShareIdRouteImport } from './routes/_app/s/$shareId'
import { Route as AppSubjectsSubjectIdRouteImport } from './routes/_app/subjects/$subjectId'
import { Route as AppScheduleScheduleWeekdayRouteImport } from './routes/_app/_schedule/schedule/$weekday'
import { Route as AppRankingsYearSeasonRouteImport } from './routes/_app/rankings/$year/$season'
import { Route as AppSubjectsSubjectIdIndexRouteImport } from './routes/_app/subjects/$subjectId/index'
import { Route as AppSubjectsSubjectIdCharactersRouteImport } from './routes/_app/subjects/$subjectId/characters'
import { Route as AppSubjectsSubjectIdPersonsRouteImport } from './routes/_app/subjects/$subjectId/persons'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/_trust',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/_schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const TrustAboutRoute = TrustAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => TrustRoute,
} as any)
const TrustPrivacyRoute = TrustPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => TrustRoute,
} as any)
const TrustTermsRoute = TrustTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => TrustRoute,
} as any)
const SitemapChaptersDotxmlRoute = SitemapChaptersDotxmlRouteImport.update({
  id: '/sitemap/chapters.xml',
  path: '/sitemap/chapters.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCharactersDotxmlRoute = SitemapCharactersDotxmlRouteImport.update({
  id: '/sitemap/characters.xml',
  path: '/sitemap/characters.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCollectionsDotxmlRoute =
  SitemapCollectionsDotxmlRouteImport.update({
    id: '/sitemap/collections.xml',
    path: '/sitemap/collections.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapPersonsDotxmlRoute = SitemapPersonsDotxmlRouteImport.update({
  id: '/sitemap/persons.xml',
  path: '/sitemap/persons.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap/static.xml',
  path: '/sitemap/static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapSubjectsDotxmlRoute = SitemapSubjectsDotxmlRouteImport.update({
  id: '/sitemap/subjects.xml',
  path: '/sitemap/subjects.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScheduleIndexRoute = AppScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppScheduleRoute,
} as any)
const AppChaptersChapterIdRoute = AppChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => AppRoute,
} as any)
const AppCharactersCharacterIdRoute =
  AppCharactersCharacterIdRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => AppRoute,
  } as any)
const AppDiscoverIndexRoute = AppDiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverTypeRoute = AppDiscoverTypeRouteImport.update({
  id: '/discover/$type',
  path: '/discover/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonsPersonIdRoute = AppPersonsPersonIdRouteImport.update({
  id: '/persons/$personId',
  path: '/persons/$personId',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsIndexRoute = AppRankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSShareIdRoute = AppSShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsSubjectIdRoute = AppSubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleScheduleWeekdayRoute =
  AppScheduleScheduleWeekdayRouteImport.update({
    id: '/schedule/$weekday',
    path: '/schedule/$weekday',
    getParentRoute: () => AppScheduleRoute,
  } as any)
const AppRankingsYearSeasonRoute = AppRankingsYearSeasonRouteImport.update({
  id: '/rankings/$year/$season',
  path: '/rankings/$year/$season',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsSubjectIdIndexRoute =
  AppSubjectsSubjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSubjectsSubjectIdRoute,
  } as any)
const AppSubjectsSubjectIdCharactersRoute =
  AppSubjectsSubjectIdCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => AppSubjectsSubjectIdRoute,
  } as any)
const AppSubjectsSubjectIdPersonsRoute =
  AppSubjectsSubjectIdPersonsRouteImport.update({
    id: '/persons',
    path: '/persons',
    getParentRoute: () => AppSubjectsSubjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppScheduleIndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$': typeof AppSplatRoute
  '/collections': typeof AppCollectionsRoute
  '/progress': typeof AppProgressRoute
  '/about': typeof TrustAboutRoute
  '/privacy': typeof TrustPrivacyRoute
  '/terms': typeof TrustTermsRoute
  '/sitemap/chapters.xml': typeof SitemapChaptersDotxmlRoute
  '/sitemap/characters.xml': typeof SitemapCharactersDotxmlRoute
  '/sitemap/collections.xml': typeof SitemapCollectionsDotxmlRoute
  '/sitemap/persons.xml': typeof SitemapPersonsDotxmlRoute
  '/sitemap/static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap/subjects.xml': typeof SitemapSubjectsDotxmlRoute
  '/chapters/$chapterId': typeof AppChaptersChapterIdRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/discover/$type': typeof AppDiscoverTypeRoute
  '/persons/$personId': typeof AppPersonsPersonIdRoute
  '/s/$shareId': typeof AppSShareIdRoute
  '/subjects/$subjectId': typeof AppSubjectsSubjectIdRouteWithChildren
  '/discover/': typeof AppDiscoverIndexRoute
  '/rankings/': typeof AppRankingsIndexRoute
  '/schedule/$weekday': typeof AppScheduleScheduleWeekdayRoute
  '/rankings/$year/$season': typeof AppRankingsYearSeasonRoute
  '/subjects/$subjectId/characters': typeof AppSubjectsSubjectIdCharactersRoute
  '/subjects/$subjectId/persons': typeof AppSubjectsSubjectIdPersonsRoute
  '/subjects/$subjectId/': typeof AppSubjectsSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppScheduleIndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$': typeof AppSplatRoute
  '/collections': typeof AppCollectionsRoute
  '/progress': typeof AppProgressRoute
  '/about': typeof TrustAboutRoute
  '/privacy': typeof TrustPrivacyRoute
  '/terms': typeof TrustTermsRoute
  '/sitemap/chapters.xml': typeof SitemapChaptersDotxmlRoute
  '/sitemap/characters.xml': typeof SitemapCharactersDotxmlRoute
  '/sitemap/collections.xml': typeof SitemapCollectionsDotxmlRoute
  '/sitemap/persons.xml': typeof SitemapPersonsDotxmlRoute
  '/sitemap/static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap/subjects.xml': typeof SitemapSubjectsDotxmlRoute
  '/chapters/$chapterId': typeof AppChaptersChapterIdRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/discover/$type': typeof AppDiscoverTypeRoute
  '/persons/$personId': typeof AppPersonsPersonIdRoute
  '/s/$shareId': typeof AppSShareIdRoute
  '/discover': typeof AppDiscoverIndexRoute
  '/rankings': typeof AppRankingsIndexRoute
  '/schedule/$weekday': typeof AppScheduleScheduleWeekdayRoute
  '/rankings/$year/$season': typeof AppRankingsYearSeasonRoute
  '/subjects/$subjectId/characters': typeof AppSubjectsSubjectIdCharactersRoute
  '/subjects/$subjectId/persons': typeof AppSubjectsSubjectIdPersonsRoute
  '/subjects/$subjectId': typeof AppSubjectsSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_trust': typeof TrustRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/_schedule': typeof AppScheduleRouteWithChildren
  '/_app/collections': typeof AppCollectionsRoute
  '/_app/progress': typeof AppProgressRoute
  '/_trust/about': typeof TrustAboutRoute
  '/_trust/privacy': typeof TrustPrivacyRoute
  '/_trust/terms': typeof TrustTermsRoute
  '/sitemap/chapters.xml': typeof SitemapChaptersDotxmlRoute
  '/sitemap/characters.xml': typeof SitemapCharactersDotxmlRoute
  '/sitemap/collections.xml': typeof SitemapCollectionsDotxmlRoute
  '/sitemap/persons.xml': typeof SitemapPersonsDotxmlRoute
  '/sitemap/static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap/subjects.xml': typeof SitemapSubjectsDotxmlRoute
  '/_app/chapters/$chapterId': typeof AppChaptersChapterIdRoute
  '/_app/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/_app/discover/$type': typeof AppDiscoverTypeRoute
  '/_app/persons/$personId': typeof AppPersonsPersonIdRoute
  '/_app/s/$shareId': typeof AppSShareIdRoute
  '/_app/subjects/$subjectId': typeof AppSubjectsSubjectIdRouteWithChildren
  '/_app/_schedule/': typeof AppScheduleIndexRoute
  '/_app/discover/': typeof AppDiscoverIndexRoute
  '/_app/rankings/': typeof AppRankingsIndexRoute
  '/_app/_schedule/schedule/$weekday': typeof AppScheduleScheduleWeekdayRoute
  '/_app/rankings/$year/$season': typeof AppRankingsYearSeasonRoute
  '/_app/subjects/$subjectId/characters': typeof AppSubjectsSubjectIdCharactersRoute
  '/_app/subjects/$subjectId/persons': typeof AppSubjectsSubjectIdPersonsRoute
  '/_app/subjects/$subjectId/': typeof AppSubjectsSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$'
    | '/collections'
    | '/progress'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/sitemap/chapters.xml'
    | '/sitemap/characters.xml'
    | '/sitemap/collections.xml'
    | '/sitemap/persons.xml'
    | '/sitemap/static.xml'
    | '/sitemap/subjects.xml'
    | '/chapters/$chapterId'
    | '/characters/$characterId'
    | '/discover/$type'
    | '/persons/$personId'
    | '/s/$shareId'
    | '/subjects/$subjectId'
    | '/discover/'
    | '/rankings/'
    | '/schedule/$weekday'
    | '/rankings/$year/$season'
    | '/subjects/$subjectId/characters'
    | '/subjects/$subjectId/persons'
    | '/subjects/$subjectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$'
    | '/collections'
    | '/progress'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/sitemap/chapters.xml'
    | '/sitemap/characters.xml'
    | '/sitemap/collections.xml'
    | '/sitemap/persons.xml'
    | '/sitemap/static.xml'
    | '/sitemap/subjects.xml'
    | '/chapters/$chapterId'
    | '/characters/$characterId'
    | '/discover/$type'
    | '/persons/$personId'
    | '/s/$shareId'
    | '/discover'
    | '/rankings'
    | '/schedule/$weekday'
    | '/rankings/$year/$season'
    | '/subjects/$subjectId/characters'
    | '/subjects/$subjectId/persons'
    | '/subjects/$subjectId'
  id:
    | '__root__'
    | '/_app'
    | '/_trust'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_app/$'
    | '/_app/_schedule'
    | '/_app/collections'
    | '/_app/progress'
    | '/_trust/about'
    | '/_trust/privacy'
    | '/_trust/terms'
    | '/sitemap/chapters.xml'
    | '/sitemap/characters.xml'
    | '/sitemap/collections.xml'
    | '/sitemap/persons.xml'
    | '/sitemap/static.xml'
    | '/sitemap/subjects.xml'
    | '/_app/chapters/$chapterId'
    | '/_app/characters/$characterId'
    | '/_app/discover/$type'
    | '/_app/persons/$personId'
    | '/_app/s/$shareId'
    | '/_app/subjects/$subjectId'
    | '/_app/_schedule/'
    | '/_app/discover/'
    | '/_app/rankings/'
    | '/_app/_schedule/schedule/$weekday'
    | '/_app/rankings/$year/$season'
    | '/_app/subjects/$subjectId/characters'
    | '/_app/subjects/$subjectId/persons'
    | '/_app/subjects/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  TrustRoute: typeof TrustRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SitemapChaptersDotxmlRoute: typeof SitemapChaptersDotxmlRoute
  SitemapCharactersDotxmlRoute: typeof SitemapCharactersDotxmlRoute
  SitemapCollectionsDotxmlRoute: typeof SitemapCollectionsDotxmlRoute
  SitemapPersonsDotxmlRoute: typeof SitemapPersonsDotxmlRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapSubjectsDotxmlRoute: typeof SitemapSubjectsDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_trust': {
      id: '/_trust'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_schedule': {
      id: '/_app/_schedule'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_trust/about': {
      id: '/_trust/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof TrustAboutRouteImport
      parentRoute: typeof TrustRoute
    }
    '/_trust/privacy': {
      id: '/_trust/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof TrustPrivacyRouteImport
      parentRoute: typeof TrustRoute
    }
    '/_trust/terms': {
      id: '/_trust/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TrustTermsRouteImport
      parentRoute: typeof TrustRoute
    }
    '/sitemap/chapters.xml': {
      id: '/sitemap/chapters.xml'
      path: '/sitemap/chapters.xml'
      fullPath: '/sitemap/chapters.xml'
      preLoaderRoute: typeof SitemapChaptersDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/characters.xml': {
      id: '/sitemap/characters.xml'
      path: '/sitemap/characters.xml'
      fullPath: '/sitemap/characters.xml'
      preLoaderRoute: typeof SitemapCharactersDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/collections.xml': {
      id: '/sitemap/collections.xml'
      path: '/sitemap/collections.xml'
      fullPath: '/sitemap/collections.xml'
      preLoaderRoute: typeof SitemapCollectionsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/persons.xml': {
      id: '/sitemap/persons.xml'
      path: '/sitemap/persons.xml'
      fullPath: '/sitemap/persons.xml'
      preLoaderRoute: typeof SitemapPersonsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/static.xml': {
      id: '/sitemap/static.xml'
      path: '/sitemap/static.xml'
      fullPath: '/sitemap/static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/subjects.xml': {
      id: '/sitemap/subjects.xml'
      path: '/sitemap/subjects.xml'
      fullPath: '/sitemap/subjects.xml'
      preLoaderRoute: typeof SitemapSubjectsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_schedule/': {
      id: '/_app/_schedule/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppScheduleIndexRouteImport
      parentRoute: typeof AppScheduleRoute
    }
    '/_app/chapters/$chapterId': {
      id: '/_app/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof AppChaptersChapterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/characters/$characterId': {
      id: '/_app/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof AppCharactersCharacterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover/': {
      id: '/_app/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof AppDiscoverIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover/$type': {
      id: '/_app/discover/$type'
      path: '/discover/$type'
      fullPath: '/discover/$type'
      preLoaderRoute: typeof AppDiscoverTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/persons/$personId': {
      id: '/_app/persons/$personId'
      path: '/persons/$personId'
      fullPath: '/persons/$personId'
      preLoaderRoute: typeof AppPersonsPersonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rankings/': {
      id: '/_app/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof AppRankingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/s/$shareId': {
      id: '/_app/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof AppSShareIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/$subjectId': {
      id: '/_app/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof AppSubjectsSubjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_schedule/schedule/$weekday': {
      id: '/_app/_schedule/schedule/$weekday'
      path: '/schedule/$weekday'
      fullPath: '/schedule/$weekday'
      preLoaderRoute: typeof AppScheduleScheduleWeekdayRouteImport
      parentRoute: typeof AppScheduleRoute
    }
    '/_app/rankings/$year/$season': {
      id: '/_app/rankings/$year/$season'
      path: '/rankings/$year/$season'
      fullPath: '/rankings/$year/$season'
      preLoaderRoute: typeof AppRankingsYearSeasonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/$subjectId/': {
      id: '/_app/subjects/$subjectId/'
      path: '/'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof AppSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof AppSubjectsSubjectIdRoute
    }
    '/_app/subjects/$subjectId/characters': {
      id: '/_app/subjects/$subjectId/characters'
      path: '/characters'
      fullPath: '/subjects/$subjectId/characters'
      preLoaderRoute: typeof AppSubjectsSubjectIdCharactersRouteImport
      parentRoute: typeof AppSubjectsSubjectIdRoute
    }
    '/_app/subjects/$subjectId/persons': {
      id: '/_app/subjects/$subjectId/persons'
      path: '/persons'
      fullPath: '/subjects/$subjectId/persons'
      preLoaderRoute: typeof AppSubjectsSubjectIdPersonsRouteImport
      parentRoute: typeof AppSubjectsSubjectIdRoute
    }
  }
}

interface AppScheduleRouteChildren {
  AppScheduleIndexRoute: typeof AppScheduleIndexRoute
  AppScheduleScheduleWeekdayRoute: typeof AppScheduleScheduleWeekdayRoute
}

const AppScheduleRouteChildren: AppScheduleRouteChildren = {
  AppScheduleIndexRoute: AppScheduleIndexRoute,
  AppScheduleScheduleWeekdayRoute: AppScheduleScheduleWeekdayRoute,
}

const AppScheduleRouteWithChildren = AppScheduleRoute._addFileChildren(
  AppScheduleRouteChildren,
)

interface AppSubjectsSubjectIdRouteChildren {
  AppSubjectsSubjectIdCharactersRoute: typeof AppSubjectsSubjectIdCharactersRoute
  AppSubjectsSubjectIdPersonsRoute: typeof AppSubjectsSubjectIdPersonsRoute
  AppSubjectsSubjectIdIndexRoute: typeof AppSubjectsSubjectIdIndexRoute
}

const AppSubjectsSubjectIdRouteChildren: AppSubjectsSubjectIdRouteChildren = {
  AppSubjectsSubjectIdCharactersRoute: AppSubjectsSubjectIdCharactersRoute,
  AppSubjectsSubjectIdPersonsRoute: AppSubjectsSubjectIdPersonsRoute,
  AppSubjectsSubjectIdIndexRoute: AppSubjectsSubjectIdIndexRoute,
}

const AppSubjectsSubjectIdRouteWithChildren =
  AppSubjectsSubjectIdRoute._addFileChildren(AppSubjectsSubjectIdRouteChildren)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppScheduleRoute: typeof AppScheduleRouteWithChildren
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppProgressRoute: typeof AppProgressRoute
  AppChaptersChapterIdRoute: typeof AppChaptersChapterIdRoute
  AppCharactersCharacterIdRoute: typeof AppCharactersCharacterIdRoute
  AppDiscoverTypeRoute: typeof AppDiscoverTypeRoute
  AppPersonsPersonIdRoute: typeof AppPersonsPersonIdRoute
  AppSShareIdRoute: typeof AppSShareIdRoute
  AppSubjectsSubjectIdRoute: typeof AppSubjectsSubjectIdRouteWithChildren
  AppDiscoverIndexRoute: typeof AppDiscoverIndexRoute
  AppRankingsIndexRoute: typeof AppRankingsIndexRoute
  AppRankingsYearSeasonRoute: typeof AppRankingsYearSeasonRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppScheduleRoute: AppScheduleRouteWithChildren,
  AppCollectionsRoute: AppCollectionsRoute,
  AppProgressRoute: AppProgressRoute,
  AppChaptersChapterIdRoute: AppChaptersChapterIdRoute,
  AppCharactersCharacterIdRoute: AppCharactersCharacterIdRoute,
  AppDiscoverTypeRoute: AppDiscoverTypeRoute,
  AppPersonsPersonIdRoute: AppPersonsPersonIdRoute,
  AppSShareIdRoute: AppSShareIdRoute,
  AppSubjectsSubjectIdRoute: AppSubjectsSubjectIdRouteWithChildren,
  AppDiscoverIndexRoute: AppDiscoverIndexRoute,
  AppRankingsIndexRoute: AppRankingsIndexRoute,
  AppRankingsYearSeasonRoute: AppRankingsYearSeasonRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface TrustRouteChildren {
  TrustAboutRoute: typeof TrustAboutRoute
  TrustPrivacyRoute: typeof TrustPrivacyRoute
  TrustTermsRoute: typeof TrustTermsRoute
}

const TrustRouteChildren: TrustRouteChildren = {
  TrustAboutRoute: TrustAboutRoute,
  TrustPrivacyRoute: TrustPrivacyRoute,
  TrustTermsRoute: TrustTermsRoute,
}

const TrustRouteWithChildren = TrustRoute._addFileChildren(TrustRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  TrustRoute: TrustRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SitemapChaptersDotxmlRoute: SitemapChaptersDotxmlRoute,
  SitemapCharactersDotxmlRoute: SitemapCharactersDotxmlRoute,
  SitemapCollectionsDotxmlRoute: SitemapCollectionsDotxmlRoute,
  SitemapPersonsDotxmlRoute: SitemapPersonsDotxmlRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapSubjectsDotxmlRoute: SitemapSubjectsDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
