/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as PersonsIndexRouteImport } from './routes/persons/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects/$subjectId'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as PersonsPersonIdRouteImport } from './routes/persons/$personId'
import { Route as EpisodesEpisodeIdRouteImport } from './routes/episodes/$episodeId'
import { Route as CharactersCharacterIdRouteImport } from './routes/characters/$characterId'
import { Route as OgTypeIdRouteImport } from './routes/og.$type.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIndexRoute = PersonsIndexRouteImport.update({
  id: '/persons/',
  path: '/persons/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsPersonIdRoute = PersonsPersonIdRouteImport.update({
  id: '/persons/$personId',
  path: '/persons/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesEpisodeIdRoute = EpisodesEpisodeIdRouteImport.update({
  id: '/episodes/$episodeId',
  path: '/episodes/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCharacterIdRoute = CharactersCharacterIdRouteImport.update({
  id: '/characters/$characterId',
  path: '/characters/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)
const OgTypeIdRoute = OgTypeIdRouteImport.update({
  id: '/og/$type/$id',
  path: '/og/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/persons/': typeof PersonsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/og/$type/$id': typeof OgTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/characters': typeof CharactersIndexRoute
  '/persons': typeof PersonsIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/og/$type/$id': typeof OgTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/persons/': typeof PersonsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/og/$type/$id': typeof OgTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters/$characterId'
    | '/episodes/$episodeId'
    | '/persons/$personId'
    | '/sitemap/xml'
    | '/subjects/$subjectId'
    | '/characters/'
    | '/persons/'
    | '/subjects/'
    | '/og/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters/$characterId'
    | '/episodes/$episodeId'
    | '/persons/$personId'
    | '/sitemap/xml'
    | '/subjects/$subjectId'
    | '/characters'
    | '/persons'
    | '/subjects'
    | '/og/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/characters/$characterId'
    | '/episodes/$episodeId'
    | '/persons/$personId'
    | '/sitemap/xml'
    | '/subjects/$subjectId'
    | '/characters/'
    | '/persons/'
    | '/subjects/'
    | '/og/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersCharacterIdRoute: typeof CharactersCharacterIdRoute
  EpisodesEpisodeIdRoute: typeof EpisodesEpisodeIdRoute
  PersonsPersonIdRoute: typeof PersonsPersonIdRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  PersonsIndexRoute: typeof PersonsIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  OgTypeIdRoute: typeof OgTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/': {
      id: '/persons/'
      path: '/persons'
      fullPath: '/persons/'
      preLoaderRoute: typeof PersonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/$personId': {
      id: '/persons/$personId'
      path: '/persons/$personId'
      fullPath: '/persons/$personId'
      preLoaderRoute: typeof PersonsPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$episodeId': {
      id: '/episodes/$episodeId'
      path: '/episodes/$episodeId'
      fullPath: '/episodes/$episodeId'
      preLoaderRoute: typeof EpisodesEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterId': {
      id: '/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof CharactersCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$type/$id': {
      id: '/og/$type/$id'
      path: '/og/$type/$id'
      fullPath: '/og/$type/$id'
      preLoaderRoute: typeof OgTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersCharacterIdRoute: CharactersCharacterIdRoute,
  EpisodesEpisodeIdRoute: EpisodesEpisodeIdRoute,
  PersonsPersonIdRoute: PersonsPersonIdRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  PersonsIndexRoute: PersonsIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  OgTypeIdRoute: OgTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
