/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap-static[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as PersonsIndexRouteImport } from './routes/persons/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects/$subjectId'
import { Route as PersonsPersonIdRouteImport } from './routes/persons/$personId'
import { Route as EpisodesEpisodeIdRouteImport } from './routes/episodes/$episodeId'
import { Route as CharactersCharacterIdRouteImport } from './routes/characters/$characterId'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as SitemapSubjectsSlugShardRouteImport } from './routes/sitemap/subjects/$slug/$shard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap-static.xml',
  path: '/sitemap-static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIndexRoute = PersonsIndexRouteImport.update({
  id: '/persons/',
  path: '/persons/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsPersonIdRoute = PersonsPersonIdRouteImport.update({
  id: '/persons/$personId',
  path: '/persons/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesEpisodeIdRoute = EpisodesEpisodeIdRouteImport.update({
  id: '/episodes/$episodeId',
  path: '/episodes/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCharacterIdRoute = CharactersCharacterIdRouteImport.update({
  id: '/characters/$characterId',
  path: '/characters/$characterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapSubjectsSlugShardRoute =
  SitemapSubjectsSlugShardRouteImport.update({
    id: '/sitemap/subjects/$slug/$shard',
    path: '/sitemap/subjects/$slug/$shard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/persons/': typeof PersonsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/sitemap/subjects/$slug/$shard': typeof SitemapSubjectsSlugShardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/characters': typeof CharactersIndexRoute
  '/persons': typeof PersonsIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/sitemap/subjects/$slug/$shard': typeof SitemapSubjectsSlugShardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/$': typeof ApiSplatRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/persons/': typeof PersonsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/sitemap/subjects/$slug/$shard': typeof SitemapSubjectsSlugShardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/api/$'
    | '/characters/$characterId'
    | '/episodes/$episodeId'
    | '/persons/$personId'
    | '/subjects/$subjectId'
    | '/characters/'
    | '/persons/'
    | '/subjects/'
    | '/sitemap/subjects/$slug/$shard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/api/$'
    | '/characters/$characterId'
    | '/episodes/$episodeId'
    | '/persons/$personId'
    | '/subjects/$subjectId'
    | '/characters'
    | '/persons'
    | '/subjects'
    | '/sitemap/subjects/$slug/$shard'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/api/$'
    | '/characters/$characterId'
    | '/episodes/$episodeId'
    | '/persons/$personId'
    | '/subjects/$subjectId'
    | '/characters/'
    | '/persons/'
    | '/subjects/'
    | '/sitemap/subjects/$slug/$shard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CharactersCharacterIdRoute: typeof CharactersCharacterIdRoute
  EpisodesEpisodeIdRoute: typeof EpisodesEpisodeIdRoute
  PersonsPersonIdRoute: typeof PersonsPersonIdRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  PersonsIndexRoute: typeof PersonsIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  SitemapSubjectsSlugShardRoute: typeof SitemapSubjectsSlugShardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-static.xml': {
      id: '/sitemap-static.xml'
      path: '/sitemap-static.xml'
      fullPath: '/sitemap-static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/': {
      id: '/persons/'
      path: '/persons'
      fullPath: '/persons/'
      preLoaderRoute: typeof PersonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/$personId': {
      id: '/persons/$personId'
      path: '/persons/$personId'
      fullPath: '/persons/$personId'
      preLoaderRoute: typeof PersonsPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/$episodeId': {
      id: '/episodes/$episodeId'
      path: '/episodes/$episodeId'
      fullPath: '/episodes/$episodeId'
      preLoaderRoute: typeof EpisodesEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$characterId': {
      id: '/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof CharactersCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/subjects/$slug/$shard': {
      id: '/sitemap/subjects/$slug/$shard'
      path: '/sitemap/subjects/$slug/$shard'
      fullPath: '/sitemap/subjects/$slug/$shard'
      preLoaderRoute: typeof SitemapSubjectsSlugShardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
  CharactersCharacterIdRoute: CharactersCharacterIdRoute,
  EpisodesEpisodeIdRoute: EpisodesEpisodeIdRoute,
  PersonsPersonIdRoute: PersonsPersonIdRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  PersonsIndexRoute: PersonsIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  SitemapSubjectsSlugShardRoute: SitemapSubjectsSlugShardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
